# Generated by Django 4.1.1 on 2022-09-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datas',
            options={'ordering': ['sensor', 'tStamp']},
        ),
        migrations.RenameField(
            model_name='datas',
            old_name='t_stamp',
            new_name='tStamp',
        ),
        migrations.RemoveField(
            model_name='datas',
            name='value',
        ),
        migrations.AddField(
            model_name='datas',
            name='airQuality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datas',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
