version: '3.7'
networks:
  rpi:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
volumes:
  mariadb_data:

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/:/mosquitto/:rw
      - ./mosquitto/log:/mosquitto/log
    environment:
      - TZ=Europe/Paris
    networks:
      rpi:
        ipv4_address: 10.5.0.10
    

  python:
    image: python:3.10.7-alpine
    container_name: python
    restart: unless-stopped
    networks:
      rpi:
        ipv4_address: 10.5.0.3
    working_dir: /app
    volumes:
      - ./python:/app
    command: sh ./start.sh
    depends_on:
      - mariadb
      - mqtt

  django:
    image: python:3.10
    container_name: django
    restart: unless-stopped
    working_dir: /django
    volumes:
      - ./django:/django
    environment:
      - TZ=Europe/Paris
    depends_on:
      - mariadb
    ports:
      - 8000:8000
    command: sh ./start.sh
    networks:
      rpi:
        ipv4_address: 10.5.0.4
  
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      rpi:
        ipv4_address: 10.5.0.2